### ISSUE TITLE
few minor issues

### ISSUE THREAD

**Issue by astroseger** [ksridharbabuus/RFAI-Contracts#1]
1. fundMembers have very similar name to foundationMembers. Maybe we could rename fundMembers to StakeMembers?

2. I would also propose to rename requestReClaim to requestTakeBackMyStake 

3. "struct Member" can be simplified to simple "unit".
    *  0 - do not exists
    * 1 - InActive/Deleted
    * 2 - Normal member
    * 3 - Admin Member who can add other members

4.  I think that, in function addOrUpdateFoundationMembers, the first require should be as following (the last “||” should be replaced with “&&”): 
```
require((owner == msg.sender || foundationMembers[msg.sender].role
== 1) && foundationMembers[msg.sender].status)
```
But it will be simplified if you accept my previous proposition.

5. In createRequest  two last lines can be replaced with:
```
emit CreateRequest(nextRequestId++, msg.sender, expiration, value, documentURI);
```

6. In all function in which you have ```Request storage req = requests[requestId]```, all ```requests[requestId]``` can be replaced with ```req``` (extendRequest, addFundsToRequest)

7. Maybe we should allow the owner of the request to add more funds without Approvment  (```require(req.status == RequestStatus.Approved);``` in addFundsToRequest means that even the owner will not be able to add more funds without Approvment)

8. approveRequest. Maybe it is better to have ```Request storage req = requests[requestId];``` (not memory!), and use ```req``` instead of ```requests[requestId]``` in the rest of the function. 

9. Why in approveRequest, the member of the foundation can change the expiration date of the request? It means that the member of the foundation can lock the funds of the creator of the request for long time... I don't think we should allow it.  I would propose to uncomment ```//require(req.expiration > block.number);```. And we should remove newExpiration parameter.

10. In all "require" in which we have ```block.number```, I would make ```block.number``` the first argument in all inequalities (but of course I do not insist). 

In  createOrUpdateSolution
```
require(block.number <= req.expiration && block.number <= req.endSubmission);
```
In vote
```
require(block.number <= req.expiration && block.number > req.endSubmission && block.number <= req.endEvaluation);
```

11. It seem that we don't need isSubmitted, isShortlisted and isClaimed in
struct Solution".
   - isSubmitted is equal to "solutionDocURI != 0"
   - isShortlisted is equal to votes[address(0)][solutionSubmitter] == 0  (actually you don't use isShortlisted at all).
   - And we don’t need isClaimed because in requestClaim we could simple set  solutionDocURI to 0. 

12.  In requestClaim you use ```div``` to calculate amount of funds. But it means that the remainder of division will be lost (if reminder of division is not 0). Of course it is very small amount (few "cogs").
But it is still not very good. I will one possible solution in the next issue.

**Comment by ksridharbabuus** [comment]
@astroseger Thanks for your detail review & suggestions. Here are quick updates:

1. changed to stakeMembers - Done
2. changed to requestClaimBack - Done
3. In general design practice we don't combine role with the status. Thats why we have it as a separate flag. Hope it should be fine.
4. Good catch, updated the logic as 
owner == msg.sender || (foundationMembers[msg.sender].role == 1 && foundationMembers[msg.sender].status)
5. Incremented in the event itself. - Done
6. Done
7. Make sense, updated the condition to allow requester to add funds before evaluation starts - Done
8. Done
9. I thought through the logic initially and commented based on the requirements discussion. Let me check and discuss with Raam
10. Changed for consistency - Done
11. isShortlisted is used in the logic to identify in case mulitple foundation members shortlist the same. It is critical in incrementing the number of unique shortlisting to avoid loops. 
Want to persist the solutionDocURI value and dont want to set to zero after claim, can used for a reference (I know we can get it from events but dont want to change it to zero)
I can remove is submitted by checking solutionDocURI value as non empty but seems to be costly comparison than the bool comparison. Will check if there is any change in the storage by removing the bool flag.
12. Will look into the second issue and will update accordingly.
Mostly the division will be after 8 decimals will be lost, but the last claim user will get this. I dont think there is something we can do rather than rounding.

Thanks again for all your feedback.

**Comment by ksridharbabuus** [comment]
All the issues mentioned are implemented in the code.
